-- Insert default subjects
INSERT INTO subjects (id, name, icon, color, description, "createdAt") VALUES
('aplikasi-skrining', 'Aplikasi Skrining', 'Search', 'emerald', 'Metodologi dan aplikasi uji tapis penapisan penyakit secara cepat dan andal pada populasi sehat.', '2026-06-01T00:00:00Z'),
('survei-cepat-epi', 'Survei Cepat Epidemiologi', 'Zap', 'sky', 'Metode pengumpulan data lapangan dengan teknik klaster 30x7 secara taktis, cepat, dan ekonomis.', '2026-06-01T00:00:00Z'),
('p-surveilans-epi', 'Praktikum Surveilans Epidemiologi', 'Activity', 'indigo', 'Pengamatan sistematis terus-menerus terhadap distribusi penyakit melalui instrumen SKDR puskesmas.', '2026-06-01T00:00:00Z'),
('manajemen-analisis-data', 'Manajemen dan Analisis Data Epidemiologi', 'Database', 'purple', 'Prinsip pengolahan data murni kesehatan, pembersihan variabel, regresi linear, dan estimasi Odd Ratio / RR.', '2026-06-01T00:00:00Z'),
('telaah-ilmiah', 'Telaah Ilmiah Epidemiologi', 'BookOpen', 'pink', 'Kritik akademis jurnal ilmiah kesehatan, mendeteksi bias riset, dan menyusun sintesis PICO.', '2026-06-01T00:00:00Z'),
('epi-penyakit-tropis', 'Epidemiologi Penyakit Tropis', 'Shield', 'amber', 'Studi persebaran, pencegahan, dan pola inang-vektor dari penyakit khas tropis seperti DBD, Malaria, dan TB.', '2026-06-01T00:00:00Z'),
('praktik-investigasi-wabah', 'Praktik Investigasi Wabah', 'Flame', 'rose', 'Langkah taktis penyelidikan kejadian luar biasa (KLB), melacak kurva epidemi, dan klasterisasi kasus.', '2026-06-01T00:00:00Z')
ON CONFLICT (id) DO NOTHING;

-- Insert default materials
INSERT INTO materials (id, "subjectId", title, content, points, formulas, flashcards, "createdAt") VALUES
('m1', 'aplikasi-skrining', 'Validitas Alat Uji Tapis Skrining', 'Uji skrining dirancang untuk mendeteksi dini penyakit pada individu asimtomatik (tanpa gejala klinis). Instrumen skrining dinilai berdasarkan validitas (Sensitivitas & Spesifisitas) serta keandalan (Reliabilitas).', '{"Sensitivitas: Proporsi orang sakit sesungguhnya yang tes skriningnya positif.","Spesifisitas: Proporsi orang sehat sesungguhnya yang tes skriningnya menunjukkan hasil negatif.","False Positive: Hasil tes menunjukkan positif padahal aslinya individu sehat."}', '{"Sensitivitas = True Positive / (True Positive + False Negative)","Spesifisitas = True Negative / (True Negative + False Positive)","Nilai Prediktif Positif = True Positive / (True Positive + False Positive)"}', '[{"id":"fc-m1-1","question":"Apa perbedaan mendasar antara Skrining dengan Diagnosis?","answer":"Skrining diuji pada kelompok populasi sehat tanpa gejala, sedangkan Diagnosis pada pasien suspek bergejala.","level":0},{"id":"fc-m1-2","question":"Tuliskan rumus Sensitivitas alat uji skrining!","answer":"Sensitivitas = True Positive / (True Positive + False Negative)","level":0},{"id":"fc-m1-3","question":"Apa konsekuensi utama jika sensitivitas tes skrining terlalu rendah?","answer":"Banyak orang sakit yang lolos saringan (False Negative tinggi), menyebabkan kegagalan deteksi dini penyakit.","level":0}]', '2026-06-01T00:00:00Z'),
('m2', 'survei-cepat-epi', 'Metode Klaster Dua Tahap WHO 30x7', 'Survei Cepat Epidemiologi (Rapid Epidemiological Assessment) adalah metode taktis lapangan untuk mendapatkan estimasi cakupan program imunisasi atau status gizi dengan waktu pengerjaan yang singkat dan biaya rendah.', '{"Menggunakan teknik sampling klaster dua tahap konvensional.","Tahap 1: Memilih 30 klaster pemukiman secara Probability Proportional to Size (PPS).","Tahap 2: Memilih secara acak sederhana minimal 7 responden per klaster.","Total ukuran sampel minimal adalah 210 responden untuk menjamin ketepatan estimasi."}', '{"Total Responden = 30 Klaster * 7 Responden = 210 Orang","Interval Kumulatif (untuk pemilihan klaster PPS) = Total Populasi / 30"}', '[{"id":"fc-m2-1","question":"Mengapa metode survei cepat 30x7 banyak dipilih di wilayah tropis miskin?","answer":"Karena tidak membutuhkan peta sampling lengkap di awal, sangat hemat biaya, dan cepat diselesaikan di lapangan.","level":0},{"id":"fc-m2-2","question":"Berapakah jumlah standar minimum responden klaster menurut pedoman WHO?","answer":"Minimal 210 responden (Didapat dari 30 Klaster ditiap klaster terdapat 7 responden).","level":0}]', '2026-06-01T00:00:00Z'),
('m3', 'p-surveilans-epi', 'Mekanisme SKDR di Puskesmas', 'Sistem Kewaspadaan Dini dan Respon (SKDR) dirancang untuk memantau tren penyakit menular berpotensi wabah secara mingguan guna segera memicu respon penanggulangan jika alarm terlewati.', '{"Laporan wajib dikirim secara mingguan (setiap hari Senin/Selasa pagi).","Variabel umum mencakup tren demam akut, diare akut, ILI (Influenza Like Illness), dan suspek campak.","Indikator kualitas surveilans: Kelengkapan (completeness) dan Ketepatan waktu (promptness)."}', '{"Kelengkapan (%) = (Jumlah Puskesmas Melapor / Total Target Puskesmas) * 100%","Ketepatan Laporan (%) = (Jumlah Laporan Tepat Waktu / Total Target Laporan) * 100%"}', '[{"id":"fc-m3-1","question":"Apa singkatan dari instrumen SKDR?","answer":"Sistem Kewaspadaan Dini dan Respon (sistem pendeteksian dini potensi wabah mingguan).","level":0},{"id":"fc-m3-2","question":"Sebutkan 3 penyakit utama yang wajib dipantau dalam lembar SKDR!","answer":"Diare Akut, Influenza Like Illness (ILI), Demam Berdarah Dengue (DBD), atau Demam Tifoid.","level":0}]', '2026-06-01T00:00:00Z'),
('m4', 'manajemen-analisis-data', 'Ukuran Kekuatan Hubungan: Odd Ratio (OR) dan Relative Risk (RR)', 'Manajemen analisis epidemiologi membedakan asosiasi berdasarkan desain studi. Studi Kasus Kontrol dianalisis dengan Odd Ratio, sedangkan Studi Kohort dianalisis dengan Relative Risk.', '{"Tabel Kontingensi 2x2 digunakan untuk merepresentasikan paparan (Exposure) dan luaran (Disease).","OR menggambarkan kemungkinan terpapar pada kelompok kasus dibanding kelompok kontrol.","Confounding adalah variabel luar yang memiliki hubungan baik dengan faktor paparan maupun disease."}', '{"Odds Ratio (OR) = (a * d) / (b * c) [Dimana a=kasus terpapar, d=kontrol tidak terpapar]","Relative Risk (RR) = [a / (a + b)] / [c / (c + d)] (mengukur insidensi kelompok terpapar vs tidak terpapar)"}', '[{"id":"fc-m4-1","question":"Kapankah kita menggunakan Odds Ratio (OR) alih-alih Relative Risk (RR)?","answer":"Saat desain penelitian yang kita gunakan adalah Case-Control (Kasus-Kontrol), di mana angka insidensi sesungguhnya tidak bisa dihitung.","level":0},{"id":"fc-m4-2","question":"Apakah yang dimaksud dengan Confounding Factor dalam analisis data?","answer":"Variabel perancu yang bias mengaburkan hubungan asosiasi sebenarnya antara paparan utama dan penyakit.","level":0}]', '2026-06-01T00:00:00Z'),
('m5', 'telaah-ilmiah', 'Critical Appraisal Artikel Jurnal Epidemiologi', 'Melakukan penelaahan kritis terhadap literatur kedokteran dan kesehatan masyarakat agar tidak terjebak hasil penelitian semu yang disebabkan kesalahan desain riset.', '{"Menggunakan panduan baku kritisi (misalnya kuesioner CASP atau STROBE).","Mengevaluasi validitas internal (metodologi bebas bias) dan validitas eksternal (generalisasi populasi).","Pernyataan PICO membantu merumuskan komponen telaah secara cepat."}', '{"PICO = Population / Patient, Intervention / Exposure, Comparison / Control, Outcome"}', '[{"id":"fc-m5-1","question":"Sebutkan 3 jenis bias utama yang harus dievaluasi saat menelaah jurnal!","answer":"Selection Bias (bias seleksi sampel), Information/Measurement Bias (bias informasi), dan Confounding Bias.","level":0},{"id":"fc-m5-2","question":"Apakah urutan teratas bukti ilmiah (Highest Hierarchy of Evidence)?","answer":"Systematic Review / Meta-analysis dari Randomised Controlled Trials (RCT).","level":0}]', '2026-06-01T00:00:00Z'),
('m6', 'epi-penyakit-tropis', 'Rantai Penularan Virus Dengue', 'Penyakit tropis menular yang disebabkan virus Dengue (famili Flaviviridae) yang ditransmisikan melalui gigitan nyamuk betina genus Aedes, terutama spesies Aedes aegypti.', '{"Trias Epidemiologi: Agent (Dengue virus), Host (Manusia), Environment (Genangan air jernih, suhu tropis).","Siklus hidup nyamuk membutuhkan genangan air buatan dalam ruangan (bak mandi, vas bunga).","Indikator keberhasilan program dikur dengan Angka Bebas Jentik."}', '{"Angka Bebas Jentik (ABJ %) = (Jumlah Rumah Bebas Jentik / Total Rumah Diperiksa) * 100%"}', '[{"id":"fc-m6-1","question":"Sebutkan nama nyamuk vektor primer penular penyakit demam berdarah dengu!","answer":"Aedes aegypti betina!","level":0},{"id":"fc-m6-2","question":"Berapakah target standar nasional program untuk Angka Bebas Jentik (ABJ)?","answer":"Harus mencapai 95% atau lebih tinggi guna mencegah ledakan siklus KLB.","level":0}]', '2026-06-01T00:00:00Z'),
('m7', 'praktik-investigasi-wabah', 'Sepuluh Langkah Investigasi KLB CDC', 'Investigasi wabah adalah penyelidikan lapangan yang dirancang untuk melacak penyebab kejadian luar biasa (KLB) penyakit agar tindakan isolasi dan penghentian paparan segera diambil.', '{"Langkah paling awal adalah mempersiapkan kerja lapangan dan memverifikasi diagnosis.","Mendefinisikan kasus secara ketat (Confirm Case, Probable Case, Suspect Case).","Menggambar Kurva Epidemi (Epidemic Curve) berdasarkan waktu timbul gejala pasien."}', '{"Attack Rate (%) = (Jumlah kasus baru pada selang waktu tertentu / Jumlah populasi berisiko) * 100%","Case Fatality Rate (CFR %) = (Jumlah kematian akibat penyakit tersebut / Total kasus penyakit tersebut) * 100%"}', '[{"id":"fc-m7-1","question":"Apakah perbedaan bentuk kurva epidemi tipe Point Source dibanding Propagated Source?","answer":"Point Source menunjukkan satu lonjakan puncak tunggal yang cepat mereda; Propagated menunjukkan serangkaian puncak beruntun seiring penularan sekunder orang-ke-orang.","level":0},{"id":"fc-m7-2","question":"Apa ukuran mortalitas klinis utama dari tingkat keganasan wabah?","answer":"Case Fatality Rate (CFR) = (Jumlah meninggal / Jumlah kasus terdiagnosis) * 100%.","level":0}]', '2026-06-01T00:00:00Z')
ON CONFLICT (id) DO NOTHING;
